

#mapping
USERID = "B1"
TIME_IN_BED = "F26"
ASSUMED_SLEEP = "F27"
ACTUAL_SLEEP_TIME = "F28"
ACTUAL_WAKE_TIME = "F30"
ACTUAL_WAKE_RATE = "F31"
SLEEP_LATENCY = "F33"
SLEEP_BOUTS = "F34"
WAKE_BOUTS = "F35"
MEAN_SLEEP_BOUTS = "F36"
MEAN_WAKE_BOUTS = "F37"
IMMOBILE_BOUTS = "F42"
MEAN_IMMOBILE_BOUTS = "F43"
LIGHTS_OUT = "G22"
FELL_ASLEEP = "G23"
WOKE_UP = "G24"
GOT_UP = "G25"
ACTUAL_SLEEP_RATE = "G29"
SLEEP_EFFICIENCY = "G32"
FRAGMENTATION_INDEX = "G49"



